In [28]:
import numpy as np

In [29]:
designers_fav_num = 10

In [41]:
empty_floor_plan = np.zeros([6,9])
rows, cols = np.indices(empty_floor_plan.shape)

intermediate_floor_plan = cols*cols + 3*cols + 2*cols*rows + rows + rows*rows
intermediate_floor_plan += designers_fav_num

binary_floor_plan = np.vectorize(np.binary_repr)(intermediate_floor_plan)
count_ones_floor_plan = np.strings.count(binary_floor_plan, '1')

floor_plan = np.where(count_ones_floor_plan % 2 == 0, "1", "0")
floor_plan = floor_plan.astype(int)

print(binary_floor_plan)
print(count_ones_floor_plan)
print(floor_plan)

[['1010' '1110' '10100' '11100' '100110' '110010' '1000000' '1010000'
  '1100010']
 ['1100' '10010' '11010' '100100' '110000' '111110' '1001110' '1100000'
  '1110100']
 ['10000' '11000' '100010' '101110' '111100' '1001100' '1011110'
  '1110010' '10001000']
 ['10110' '100000' '101100' '111010' '1001010' '1011100' '1110000'
  '10000110' '10011110']
 ['11110' '101010' '111000' '1001000' '1011010' '1101110' '10000100'
  '10011100' '10110110']
 ['101000' '110110' '1000110' '1011000' '1101100' '10000010' '10011010'
  '10110100' '11010000']]
[[2 3 2 3 3 3 1 2 3]
 [2 2 3 2 2 5 4 2 4]
 [1 2 2 4 4 3 5 4 2]
 [3 1 3 4 3 4 3 3 5]
 [4 3 3 2 4 5 2 4 5]
 [2 4 3 3 4 2 4 4 3]]
[[1 0 1 0 0 0 0 1 0]
 [1 1 0 1 1 0 1 1 1]
 [0 1 1 1 1 0 0 1 1]
 [0 0 0 1 0 1 0 0 0]
 [1 0 0 1 1 0 1 1 0]
 [1 1 0 0 1 1 1 1 0]]
