In [1]:
import numpy as np

In [2]:
day3_map = [] 
day3_inputs = "inputs/day3.txt"
with open(day3_inputs) as file:
    day3_map = file.readlines()

In [11]:
# part 1
# read each map row, use list top split out into characters, then convert to 
map_row_length = len(list(day3_map[0].strip()))
map_total_rows = len(day3_map)

map_array = np.zeros([map_total_rows, map_row_length])

# convert open space "." into "0", i.e., leave as zero
# convert tree "#" into "7" because it looks like a tree
# tree encounter can be represented by NaN

for i in range(len(day3_map)):
    curr_row = day3_map[i]
    curr_row_split = list(curr_row.strip())
    
    for j in range(len(curr_row_split)):
        curr_tile = curr_row_split[j]
        
        if curr_tile == "#":
            map_array[i][j] = 7

In [24]:
print(map_array)

[[0. 0. 0. ... 0. 0. 7.]
 [7. 7. 0. ... 7. 0. 0.]
 [0. 0. 0. ... 0. 7. 7.]
 ...
 [0. 0. 0. ... 0. 0. 7.]
 [7. 7. 7. ... 0. 7. 0.]
 [0. 0. 0. ... 0. 7. 0.]]


In [26]:
# right 3 and down 1 from top left

curr_location = np.array([0,0]) # X, Y

# 1) while loop
# 2) each round add 3 to X, and 1 to Y
# 3) then check that index in map_array on whether there is a tree
# 4) stop when there is an error, i.e., no more map_array rows

encountered_trees = 0

try:
    while 1 > 0:
        curr_location[0] += 3
        curr_location[1] += 1

        # check map array
        curr_loc_tile = map_array[curr_location[1]][curr_location[0]]
        print(curr_location, curr_loc_tile)
        if curr_loc_tile == 7:
            encountered_trees += 1
except IndexError:
    print(encountered_trees)

[3 1] 7.0
[6 2] 7.0
[9 3] 7.0
[12  4] 7.0
[15  5] 0.0
[18  6] 7.0
[21  7] 7.0
[24  8] 0.0
[27  9] 7.0
[30 10] 7.0
8


In [40]:
# i'm getting the wrong answer because the map extends/repeats the right!
# i didnt read the brief properly again hahahahahah

# how many times would i need to duplicate the current map "column" for?
# is there a way to calculate? yes, the current map stops at around 30 columns
# the map goes down to about 300 rows, therefore i can take the total row 
# number and divide by the total columns, then round up to find 

num_rows = len(map_array)
num_col = map_row_length
multi_factor = int(np.ceil(num_rows / num_col))

map_array_extended = np.tile(map_array, multi_factor*10)

In [41]:
# right 3 and down 1 from top left

curr_location = np.array([0,0]) # X, Y

# 1) while loop
# 2) each round add 3 to X, and 1 to Y
# 3) then check that index in map_array on whether there is a tree
# 4) stop when there is an error, i.e., no more map_array rows

encountered_trees = 0

try:
    while 1 > 0:
        curr_location[0] += 3
        curr_location[1] += 1

        # check map array
        curr_loc_tile = map_array_extended[curr_location[1]][curr_location[0]]
        print(curr_location, curr_loc_tile)
        if curr_loc_tile == 7:
            encountered_trees += 1
except IndexError:
    print(encountered_trees)

[3 1] 7.0
[6 2] 7.0
[9 3] 7.0
[12  4] 7.0
[15  5] 0.0
[18  6] 7.0
[21  7] 7.0
[24  8] 0.0
[27  9] 7.0
[30 10] 7.0
[33 11] 0.0
[36 12] 7.0
[39 13] 0.0
[42 14] 7.0
[45 15] 7.0
[48 16] 7.0
[51 17] 7.0
[54 18] 7.0
[57 19] 7.0
[60 20] 7.0
[63 21] 7.0
[66 22] 7.0
[69 23] 0.0
[72 24] 0.0
[75 25] 7.0
[78 26] 7.0
[81 27] 7.0
[84 28] 0.0
[87 29] 7.0
[90 30] 7.0
[93 31] 7.0
[96 32] 7.0
[99 33] 7.0
[102  34] 0.0
[105  35] 7.0
[108  36] 7.0
[111  37] 7.0
[114  38] 7.0
[117  39] 7.0
[120  40] 7.0
[123  41] 7.0
[126  42] 7.0
[129  43] 7.0
[132  44] 0.0
[135  45] 7.0
[138  46] 7.0
[141  47] 7.0
[144  48] 7.0
[147  49] 7.0
[150  50] 7.0
[153  51] 7.0
[156  52] 7.0
[159  53] 7.0
[162  54] 7.0
[165  55] 0.0
[168  56] 7.0
[171  57] 7.0
[174  58] 7.0
[177  59] 7.0
[180  60] 7.0
[183  61] 7.0
[186  62] 7.0
[189  63] 7.0
[192  64] 7.0
[195  65] 7.0
[198  66] 7.0
[201  67] 7.0
[204  68] 7.0
[207  69] 7.0
[210  70] 7.0
[213  71] 7.0
[216  72] 7.0
[219  73] 7.0
[222  74] 7.0
[225  75] 7.0
[228  76] 7.0
[231  77

In [37]:
print(map_total_rows)

323


In [42]:
# 276 is the correct answer! i just need to increase the width of the map by a
# very large amount! i need to generalise the width so that it's able to be an acceptable number

In [53]:
# part 2

def tree_finder(selected_route):
    right = selected_route[0]
    down = selected_route[1]

    curr_location = np.array([0,0]) # X, Y
    encountered_trees = 0
    try:
        while 1 > 0:
            curr_location[0] += right
            curr_location[1] += down

            # check map array
            curr_loc_tile = map_array_extended[curr_location[1]][curr_location[0]]
            if curr_loc_tile == 7:
                encountered_trees += 1
    except IndexError:
        return encountered_trees
        
routes = [
    [1,1],
    [3,1],
    [5,1],
    [7,1],
    [1,2]
]

total_encountered_trees = []
for route_key, route_value in enumerate(routes):
    curr_encountered_trees = tree_finder(route_value)
    total_encountered_trees.append(curr_encountered_trees) 
    
# total_encountered_trees = np.asarray(total_encountered_trees)
multiplied_tet = np.prod(total_encountered_trees)
print(multiplied_tet)

7812180000
